### PR TITLE
Add notes about Jupyter and Docker

### PR DESCRIPTION
**Pull request by kevinrobinson**
Jupyter is from data analysis work on Teacher Moments, Docker for dependencies in that project and other smaller experiments.

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@kesiena115 Can you review?

**Comment by kevinrobinson** [comment]
@kesiena115 Can you take a look at this?

**Comment by kesiena115** [comment]
@kevinrobinson looks good to me

**Comment by kevinrobinson** [comment]
thanks!

**Pull request merged**
